src/Entity/Evenements.php
<?php

namespace App\Entity;

use App\Repository\EvenementsRepository;
use App\Trait\SlugTrait;
use DateTimeImmutable;
use Doctrine\Common\Collections\ArrayCollection;
    use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\DateTimeType;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Form\Extension\Core\Type\DateType;

#[ORM\Entity(repositoryClass: EvenementsRepository::class)]
class Evenements
{
    
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $libelle = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $description = null;

    #[ORM\Column(options : ['default' => 'CURRENT_TIMESTAMP'])]
    private ?\DateTimeImmutable $created_at = null;

    #[ORM\ManyToOne(inversedBy: 'evenements')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Categories $categorie = null;

    #[ORM\OneToMany(mappedBy: 'evenement', targetEntity: TypeBillets::class)]
    private Collection $typeBillets;

    #[ORM\Column]
    private ?int $places = null;

    #[ORM\Column(length: 255)]
    private ?string $slug = null;

    #[ORM\Column]
    private ?int $prix_V = null;
    
    #[ORM\Column]
    private ?int $prix_SV = null;
    
    #[ORM\Column]
    private ?int $prix_N = null;

    #[ORM\Column(options : ['default' => 'CURRENT_TIMESTAMP'])]
    private ?\DateTimeImmutable $date_e = null;

    #[ORM\OneToMany(mappedBy: 'evenement', targetEntity: ImagesEvent::class)]
    private Collection $imagesEvents;

    #[ORM\OneToMany(mappedBy: 'evenement', targetEntity: Commande::class, orphanRemoval: true)]
    private Collection $commandes;

    public function __construct()
    {
        $this->typeBillets = new ArrayCollection();
        $this->created_at = new \DateTimeImmutable();
        $this->imagesEvents = new ArrayCollection();
        $this->date_e = new \DateTimeImmutable();
        $this->commandes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLibelle(): ?string
    {
        return $this->libelle;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }
    
    public function getCategorie(): ?Categories
    {
        return $this->categorie;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function getPrixV(): ?int
    {
        return $this->prix_V;
    }

    public function getPrixSV(): ?int
    {
        return $this->prix_SV;
    }
    
    public function getPrixN(): ?int
    {
        return $this->prix_N;
    }
    
    public function getDateE(): ?\DateTimeImmutable
    {
        return $this->date_e;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function setLibelle(string $libelle): static
    {
        $this->libelle = $libelle;

        return $this;
    }
    public function setPrixV(int $prix_V): static
    {
        $this->prix_V = $prix_V;

        return $this;
    }
    public function setPrixN(int $prix_N): static
    {
        $this->prix_N = $prix_N;

        return $this;
    }

    public function setPrixSV(int $prix_SV): static
    {
        $this->prix_SV = $prix_SV;

        return $this;
    }

    public function setDateE(\DateTimeImmutable $date_e): static
    {
        $this->date_e = $date_e;

        return $this;
    }

    public function setCategorie(?Categories $categorie): static
    {
        $this->categorie = $categorie;

        return $this;
    }


    /**
     * @return Collection<int, TypeBillets>
     */
    public function getTypeBillets(): Collection
    {
        return $this->typeBillets;
    }

    public function addTypeBillet(TypeBillets $typeBillet): static
    {
        if (!$this->typeBillets->contains($typeBillet)) {
            $this->typeBillets->add($typeBillet);
            $typeBillet->setEvenement($this);
        }

        return $this;
    }

    public function removeTypeBillet(TypeBillets $typeBillet): static
    {
        if ($this->typeBillets->removeElement($typeBillet)) {
            // set the owning side to null (unless already changed)
            if ($typeBillet->getEvenement() === $this) {
                $typeBillet->setEvenement(null);
            }
        }

        return $this;
    }

    public function getPlaces(): ?int
    {
        return $this->places;
    }

    public function setPlaces(int $places): static
    {
        $this->places = $places;

        return $this;
    }
    
    public function setCreatedAt(\DateTimeImmutable $created_at): static
    {
        $this->created_at = $created_at;

        return $this;
    }
    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    /**
     * @return Collection<int, ImagesEvent>
     */
    public function getImagesEvents(): Collection
    {
        return $this->imagesEvents;
    }

    public function addImagesEvent(ImagesEvent $imagesEvent): static
    {
        if (!$this->imagesEvents->contains($imagesEvent)) {
            $this->imagesEvents->add($imagesEvent);
            $imagesEvent->setEvenement($this);
        }

        return $this;
    }

    public function removeImagesEvent(ImagesEvent $imagesEvent): static
    {
        if ($this->imagesEvents->removeElement($imagesEvent)) {
            // set the owning side to null (unless already changed)
            if ($imagesEvent->getEvenement() === $this) {
                $imagesEvent->setEvenement(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Commande>
     */
    public function getCommandes(): Collection
    {
        return $this->commandes;
    }

    public function addCommande(Commande $commande): static
    {
        if (!$this->commandes->contains($commande)) {
            $this->commandes->add($commande);
            $commande->setEvenement($this);
        }

        return $this;
    }

    public function removeCommande(Commande $commande): static
    {
        if ($this->commandes->removeElement($commande)) {
            // set the owning side to null (unless already changed)
            if ($commande->getEvenement() === $this) {
                $commande->setEvenement(null);
            }
        }

        return $this;
    }
}

src/Controller/EvenementController.php
<?php

namespace App\Controller;

use App\Entity\Evenements;
use App\Form\EvenementsFormType;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\String\Slugger\SluggerInterface;

#[Route('/evenements', name: 'evenements_')]
class EvenementController extends AbstractController
{
    #[Route('/ajout', name: 'ajout')]
    public function ajout(Request $request, EntityManagerInterface $em, SluggerInterface $slugger)
    {
        $evenement = new Evenements();

        $evenementForm = $this->createForm(EvenementsFormType::class, $evenement);

        $evenementForm->handleRequest($request);

        // dd($evenementForm);
        if($evenementForm->isSubmitted() && $evenementForm->isValid()) {
            $slug = $slugger->slug($evenement->getLibelle());
            $evenement->setSlug($slug);

            $em->persist($evenement);
            $em->flush();

            $this->addFlash('success', 'L\'événement a bien été ajouté');

            return $this->redirectToRoute('categories_list', array('slug' => $evenement->getCategorie()->getSlug()));
        }


        return $this->render('evenement/ajout.html.twig', [
            'evenementForm' => $evenementForm->createView()
        ]);

    }
    #[Route('/{slug}', name: 'details')]
    public function index(Evenements $evenement): Response
    {
        return $this->render('evenement/details.html.twig', compact('evenement')
        );
    }
}

templates/evenement/_form.html.twig
{{form_start(evenementForm)}}
{{form_row(evenementForm.libelle)}}
{{form_row(evenementForm.description)}}
{{form_row(evenementForm.categorie)}}
{{form_row(evenementForm.places)}}
{{form_row(evenementForm.date_e)}}
{{form_row(evenementForm.prix_V)}}
{{form_row(evenementForm.prix_SV)}}
{{form_row(evenementForm.prix_N)}}
<button type="submit" class="btn btn-primary">Ajouter</button>
{{form_end(evenementForm)}}

templates/evenement/ajout.html.twig
{% extends "base.html.twig" %}

{% block body %}
	<main class="container">
		<div class="row">
			<h1 class="my-4">Ajout de l'événement</h1>
			<div class="col-12">
				{% include "evenement/_form.html.twig" %}
			</div>
		</div>
	</main>
{% endblock %}

templates/evenement/details.html.twig
{% include "base.html.twig" %}

{% block body %}
	<main class="container">
		<section class="row">
			<div class="col-12">
				<h1>
					<strong>Evénement :
					</strong>
					{{ evenement.libelle }}
				</h1>
			</div>
			<div class="col-6">
				<img src="{{ asset('assets/uploads/')}}">
				Images
			</div>
			<div class="col-6">
				<p>{{evenement.description}}</p>
				<p>
					<strong>Categorie :</strong>
					{{evenement.categorie.libelle}}
				</p>
				<p>
					<strong>Prix :</strong>
					<br>Normal :
					{{evenement.prixN}}
					{% if evenement.prixSV > 0 %}
						<br>Semi-Vip :
						{{evenement.prixSV}}
					{% endif %}

					<br>VIP :
					{{evenement.prixV}}
				</p>
				<p>
					<strong>Date :</strong>
					{{evenement.dateE|date('d/m/Y H:i')}}
				</p>
				{% if evenement.places > 0 %}
					<strong>Acheter</strong>
					<br>
					{% if evenement.prixV != 0 %}
						<a href="{{path('achat_ajouter', {id: evenement.id, prix: 'prixV'})}}" class="btn btn-success">VIP</a>
					{% endif %}
					{% if evenement.prixSV != 0 %}
						<a href="{{path('achat_ajouter', {id: evenement.id, prix: 'prixSV'})}}" class="btn btn-success">Semi-VIP</a>
					{% endif %}
					{% if evenement.prixN != 0 %}
						<a href="{{path('achat_ajouter', {id: evenement.id, prix: 'prixN'})}}" class="btn btn-success">Normal</a>
					{% endif %}
				{% else %}
					<p class="text-danger">Toutes les places sont prises</p>
				{% endif %}


			</div>
		</section>
	</main>
{% endblock %}

templates/evenement/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello AcceuilController!
{% endblock %}


{% block body %}
	<main class="container">
		<section class="row">
			{% if utilisateur == 'admin' %}
				<a href="#" class="btn btn-primary my-3">Ajouter des événements</a>
			{% endif %}
			<h1>Liste des événements de a</h1>
			{% for i in 0..7 %}
				<div class="col-3 mb-3 my-3">
					<article class="card h-100">
						<div class="card-body">
							<h2 class="card-title">Un événement</h2>
							<p class="card-text">Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad ut ea illo, nisi laudantium saepe nostrum ipsa nam magnam. Maxime?</p>
							<a href="#" class="btn btn-primary">Détails</a>
						</div>
					</article>
				</div>
			{% endfor %}
		</section>
	</main>
{% endblock %}